	gcc -o cardtest1 cardtest1.c dominion.c rngs.c -lm
	gcc -o cardtest2 cardtest2.c dominion.c rngs.c -lm
	gcc -o randomtestcard1 randomtestcard1.c dominion.c rngs.c -lm
	gcc -o randomtestadventurer randomtestadventurer.c dominion.c rngs.c -lm
	
	./cardtest1
	./cardtest2
	./randomtestcard1
	./randomtestadventurer
